# "adi_gpu" crate - Licensed under the MIT LICENSE
#  * Copyright (c) 2017-2018  Jeron A. Lau <jeron.lau@plopgrizzly.com>

[package]
name = "minimal"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeron.lau@plopgrizzly.com>"]

[dependencies]
adi_gpu = { path = "../../" }
aci_png = "^0.6"
