# Aldaron's Device Interface / GPU                                             #
# Copyright (c) 2017 Plop Grizzly, Jeron Lau <jeron.lau@plopgrizzly.com>       #
# Licensed under the MIT LICENSE                                               #
#                             _        _                                       #
#                            /@\——————/@\                                      #
# .———  .                   |   o    o   |     .————      .            .       #
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   . #
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   | #
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /  #
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |   #
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |   #
#                 |        \              /                              __/   #
#                           ¯————————————¯                                     #
# Cargo.toml                                                                   #

################################################################################

[package]
name = "adi_gpu"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeron.lau@plopgrizzly.com>", "Douglas P Lau"]

################################################################################

license = "MIT"
documentation = "https://docs.rs/adi_gpu"
homepage = "http://plopgrizzly.com/adi_gpu"
repository = "https://github.com/plopgrizzly/adi_gpu"

################################################################################

readme = "README.md"
description = """
    Aldaron's Device Interface / GPU is a library developed by Plop Grizzly for
    interfacing with the GPU to render graphics or do fast calculations.
"""
keywords = ["vulkan", "graphics", "rendering", "opengl", "gpu"]
categories = ["rendering::graphics-api", "hardware-support",
	"rendering::engine", "rendering", "no-std"]

################################################################################

exclude = ["examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore"]
build = "build.rs"

################################################################################

[dependencies]
afi = "^0.3"
ami = "^0.5"
awi = { path = "../awi" }
asi_vulkan = { path = "../asi_vulkan" }

[build-dependencies.gcc]
version = "0.3.50"

[features]
checks = ["asi_vulkan/checks"]
validation = ["asi_vulkan/validation"]

################################################################################
