[package]
name = "minimal"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeron.lau@plopgrizzly.tech>"]

[dependencies]
adi_gpu = { path = "../../" }
aci_png = "^0.2"

# Enable checks & validation
[features]
default = []
checks = ["adi_gpu/checks"]
validation = ["adi_gpu/validation"]
